### ISSUE TITLE
MVP - TODO

### ISSUE THREAD

**Issue by jamesmorgan** [andygray/adminfire#28]
* [ ] Gulp Build Scripts
 * [ ] Ability to start in prod/dev mode and point to different firebase endpoint
* [ ] Populate sites form with required fields to capture
* [ ] Add suppliers CRUD page - https://github.com/andygray/adminfire/pull/27
* [ ] Site Contract -> Suppliers relationship
* [ ] Load data - (reuse browser API's)
* [ ] Chatter box
* [ ] Finish dashboard landing page

**Comment by andygray** [comment]
updated list!
